services:
  nginx:
    build:
      context: https://github.com/hulaneoTi/Container-nginx.git
      dockerfile: nginx-dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
